### ISSUE TITLE
service mariadb 10.3.x does not start

### ISSUE THREAD

**Issue by dmglab** [bertvv/ansible-role-mariadb#14]
since MariaDB 10.3.1 the following config properties has been removed
`mariadb_innodb_file_format` and `mariadb_innodb_file_format_check`

**Comment by huglester** [comment]
maybe you had a time for a new release?

**Comment by bertvv** [comment]
Thank you for your intrest, Jaroslav! Since you asked so nicely, I'll do my
best! 😉

**Comment by bertvv** [comment]
Fixed in v2.1.0 that I just released on Ansible Galaxy!
Sorry it took so long!

**Comment by huglester** [comment]
Thank you 8)
