### ISSUE TITLE
Cannot install role

### ISSUE THREAD

**Issue by fakhriperdana** [bertvv/ansible-role-mariadb#25]
I try to do `ansible-galaxy install bertvv.mariadb`, but unfortunately it output this

<img width="653" alt="Screen Shot 2019-07-24 at 19 53 39" src="https://user-images.githubusercontent.com/22459355/61795125-e4bf4a80-ae4c-11e9-8b6e-569465f7f4b1.png">

I tried to search for answers here but I find to solutions, can someone help me? Thanks

**Comment by bertvv** [comment]
Can you try again showing the full traceback, as suggested by the error message? I'm suspecting this is an error in the ansible-galaxy command, not in the role itself...

**Comment by bertvv** [comment]
I'm closing this since I didn't get any followup on this. I suppose the problem was solved, or you switched to another role...
