### ISSUE TITLE
Enhancement : Store template file names in variables

### ISSUE THREAD

**Issue by ghost** [bertvv/ansible-role-mariadb#27]
Hello,

In order to be able to use customized versions of the cnf templates, would it be possible to store each file name in a variable so they can be overloaded in a playbook?

Thank you in advance.

Kind regards,

**Comment by bertvv** [comment]
Sorry, I don't understand your question. Can you elaborate?

**Comment by bertvv** [comment]
Since I got no reply, I'm closing this
