### ISSUE TITLE
root-password.yml - Not vault compatible

### ISSUE THREAD

**Issue by pbalu-code** [bertvv/ansible-role-mariadb#40]
FAILED! => {"msg": "The conditional check 'mariadb_root_password | length == 0' failed. The error was: Unexpected templating type error occurred on ({% if mariadb_root_password | length == 0 %} True {% else %} False {% endif %}): object of type 'AnsibleVaultEncryptedUnicode' has no len()\n\n

Here is the fix:

```
- name: Check if a custom root password is specified
  debug:
    msg: >
      Warning!! the MariaDB root password was left empty. Please set a custom
      password with role variable mariadb_root_password to secure your database
      server!
#  when: mariadb_root_password | length == 0   ---It is not Vault compatible
  when: mariadb_root_password == ''
```

**Comment by bertvv** [comment]
Comparing with the empty string gave me an `ansible-lint` warning. I modified the conditional to:

```yaml
when: not mariadb_root_password
```

I will release a new version with this (and other) changes shortly. When I do, can you check if the change is sufficient? I'm keeping this issue open for the time being.

**Comment by pbalu-code** [comment]
Never mind... :-)
