### ISSUE TITLE
Setting up root Password

### ISSUE THREAD

**Issue by Rahulsharma0810** [bertvv/ansible-role-mariadb#9]
I am getting, when trying to pass root password in
```
# roles/mariadb/defaults/main.yml 
mariadb_root_password: 'secure'
```

```
TASK [Mariadb : Set MariaDB root password for the first time] ************************************************************************************
fatal: [271.AppDevelopment.server]: FAILED! => {"changed": false, "failed": true, "msg": "(1133, \"Can't find any matching row in the user table\")"}
        to retry, use: --limit @/Users/rvs/Repositories/Ansible/playbook.retry
```

**Comment by bertvv** [comment]
I cannot reproduce this error, can you provide some more information? A minimal failing playbook would help.

I set up a Vagrant test environment with v2.0.1 of this role and the following playbook:

```Yaml
# site.yml
---
- hosts: srv001
  become: true
  vars:
    mariadb_root_password: 'secure'
  roles:
    - bertvv.mariadb
```

In my test setup, this playbook finishes without errors, and `mysql -uroot -psecure mysql` works as expected.

The error message "Can't find any matching row in the user table" suggests that the root user doesn't exist anymore? Was the playbook applied on a clean installation?

**Comment by bertvv** [comment]
Since I haven't heard back from you, @Rahulsharma0810, I assume this isn't relevant anymore. I'm going to close this issue. Feel free to report it again if this still causes you problems, if possible with a minimal playbook that reproduces the error.
